### PR TITLE
56 api support

### LINKED ISSUE #56: APIs Support
- [ ] Add api function defintion

### PR DESCRIPTION
**Pull request by 1hachem**
add api support in toolkit
closes #56

### CODE REVIEW

**Comment by 1hachem** [comment]
@strlrd-29 please review this

**Comment by 1hachem** [comment]
so far its working for native types (str, int, float, dict and list)
on the toolkit side I will be adding cohere, openai and search apis inchalah for tiaret release

**Comment by 1hachem** [comment]
next release I will work inchalah on supporting image, audio and video types by saving to a CM ... CDN got you ! you thought I was goint to say CMS 🌵

**Comment by 1hachem** [comment]
@strlrd-29 please review this

**Review by strlrd-29 — APPROVED** [review]

**Pull request merged**
